import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>RAC Logistics</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight sm:text-[5rem]">
            RAC Logistics
          </h1>
        </div>
      </main>
    </>
  );
}
