import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>RAC Logistics</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-brand">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <h1 className="display-sm md:display-md lg:display-lg text-white">
            RAC Logistics
          </h1>
          <h1 className="display-lg text-white">
            Display Large - Roboto 57/64 . 0
          </h1>
          <h1 className="display-md text-white">
            Display Large - Roboto 45/52 . 0
          </h1>
          <h1 className="display-sm text-white">
            Display Large - Roboto 36/44 . 0
          </h1>
        </div>
      </main>
    </>
  );
}
