import {
  type AutoImportOrderPackageType,
  type AutoImportRequestPackageType,
} from "~/contexts/AutoImportContext";
import {
  type ExportOrderPackageType,
  type ExportRequestPackageType,
} from "~/contexts/ExportContext";
import {
  type ImportOrderPackageType,
  type ImportRequestPackageType,
} from "~/contexts/ImportContext";
import { type NotificationItemType } from "~/contexts/NotificationContext";
import {
  type ShopOrderPackageType,
  type ShopRequestPackageType,
} from "~/contexts/ShopContext";

const src = "https://placehold.co/500x500/cac4d0/1d192b?text=Image";

export const shopOrders: ShopOrderPackageType[] = [
  {
    orderId: "OD08751",
    orderStatus: "processed",
    orderLocalDate: new Date("2023/1/23").toLocaleString(),
    trackingId: "SH08751",
    shippingStatus: "not started",
    totalShopForMeCost: 107.76,
    shopForMeStatus: "Purchase not started",
    totalShippingCost: 107.76,
    shippingPaymentStatus: "Unpaid",
    originWarehouse: "Nigeria Warehouse (Lagos)",
    items: [
      {
        store: "Amazon",
        urgent: false,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        shippingCost: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
      {
        store: "Aliexpress",
        urgent: true,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        shippingCost: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
    ],
    shipmentDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
  },
  {
    orderId: "OD08752",
    orderStatus: "processed",
    orderLocalDate: new Date("2023/2/23").toLocaleString(),
    trackingId: "SH08752",
    shippingStatus: "arrived destination",
    totalShopForMeCost: 107.76,
    shopForMeStatus: "Purchase in progress",
    totalShippingCost: 107.76,
    shippingPaymentStatus: "Paid",
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        store: "Amazon",
        urgent: false,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        shippingCost: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
      {
        store: "Aliexpress",
        urgent: true,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        shippingCost: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
      {
        store: "Others",
        urgent: true,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        shippingCost: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
    ],
    shipmentDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
  },
  {
    orderId: "OD08753",
    orderStatus: "processed",
    orderLocalDate: new Date("2023/3/23").toLocaleString(),
    trackingId: "SH08753",
    shippingStatus: "ready for shipping",
    totalShopForMeCost: 107.76,
    shopForMeStatus: "Purchase completed",
    totalShippingCost: 107.76,
    shippingPaymentStatus: "Unpaid",
    originWarehouse: "China Warehouse (Guangzhou city)",
    items: [
      {
        store: "Amazon",
        urgent: false,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        shippingCost: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
      {
        store: "Aliexpress",
        urgent: true,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        shippingCost: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
      {
        store: "Others",
        urgent: true,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        shippingCost: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
      {
        store: "Others",
        urgent: true,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        shippingCost: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
    ],
    shipmentDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
  },
  {
    orderId: "OD08754",
    orderStatus: "processed",
    orderLocalDate: new Date("2023/4/23").toLocaleString(),
    trackingId: "SH08754",
    shippingStatus: "in transit",
    totalShopForMeCost: 107.76,
    shopForMeStatus: "Purchase completed",
    totalShippingCost: 107.76,
    shippingPaymentStatus: "Paid",
    originWarehouse: "Dubai Warehouse",
    items: [
      {
        store: "Amazon",
        urgent: false,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        shippingCost: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
      {
        store: "Aliexpress",
        urgent: true,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        shippingCost: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
      {
        store: "Others",
        urgent: true,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        shippingCost: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
      {
        store: "Others",
        urgent: true,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        shippingCost: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
      {
        store: "Others",
        urgent: true,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        shippingCost: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
    ],
    shipmentDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
  },
  {
    orderId: "OD08755",
    orderStatus: "processed",
    orderLocalDate: new Date("2023/5/23").toLocaleString(),
    trackingId: "SH08755",
    shippingStatus: "processing",
    totalShopForMeCost: 107.76,
    shopForMeStatus: "Purchase completed",
    totalShippingCost: 107.76,
    shippingPaymentStatus: "Paid",
    originWarehouse: "UK Warehouse (London)",
    items: [
      {
        store: "Amazon",
        urgent: false,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        shippingCost: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
    ],
    shipmentDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
  },
  {
    orderId: "OD08756",
    orderStatus: "processed",
    orderLocalDate: new Date("2023/6/23").toLocaleString(),
    trackingId: "SH08756",
    shippingStatus: "cleared",
    totalShopForMeCost: 107.76,
    shopForMeStatus: "Purchase completed",
    totalShippingCost: 107.76,
    shippingPaymentStatus: "Paid",
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        store: "Amazon",
        urgent: false,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        shippingCost: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
    ],
    shipmentDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
  },
  {
    orderId: "OD08757",
    orderStatus: "processed",
    orderLocalDate: new Date("2023/7/23").toLocaleString(),
    trackingId: "SH08757",
    shippingStatus: "cancelled",
    totalShopForMeCost: 107.76,
    shopForMeStatus: "Purchase not started",
    totalShippingCost: 107.76,
    shippingPaymentStatus: "Unpaid",
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        store: "Amazon",
        urgent: false,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        shippingCost: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
    ],
    shipmentDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
  },
  {
    orderId: "OD08758",
    orderStatus: "processed",
    orderLocalDate: new Date("2023/8/23").toLocaleString(),
    trackingId: "SH08758",
    shippingStatus: "delivered",
    totalShopForMeCost: 107.76,
    shopForMeStatus: "Purchase completed",
    totalShippingCost: 107.76,
    shippingPaymentStatus: "Paid",
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        store: "Amazon",
        urgent: false,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        shippingCost: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
    ],
    shipmentDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
  },
];

export const shopRequests: ShopRequestPackageType[] = [
  {
    requestId: "OD08751",
    requestStatus: "Not Responded",
    requestLocalDate: new Date().toLocaleString(),
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        store: "Amazon",
        urgent: false,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        shippingCost: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
    ],
    totalShopForMeCost: 87000,
  },
  {
    requestId: "OD08752",
    requestStatus: "Responded",
    requestLocalDate: new Date().toLocaleString(),
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        store: "Amazon",
        urgent: false,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        shippingCost: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
    ],
    totalShopForMeCost: 87000,
  },
  {
    requestId: "OD08753",
    requestStatus: "Not Responded",
    requestLocalDate: new Date().toLocaleString(),
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        store: "Amazon",
        urgent: false,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        shippingCost: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
    ],
    totalShopForMeCost: 87000,
  },
  {
    requestId: "OD08754",
    requestStatus: "Responded",
    requestLocalDate: new Date().toLocaleString(),
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        store: "Amazon",
        urgent: false,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        shippingCost: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
    ],
    totalShopForMeCost: 87000,
  },
  {
    requestId: "OD08755",
    requestStatus: "Not Responded",
    requestLocalDate: new Date().toLocaleString(),
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        store: "Amazon",
        urgent: false,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        shippingCost: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
    ],
    totalShopForMeCost: 87000,
  },
  {
    requestId: "OD08756",
    requestStatus: "Responded",
    requestLocalDate: new Date().toLocaleString(),
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        store: "Amazon",
        urgent: false,
        url: "htttp/jjnkkukja.jhgyjayjdjjhcjc",
        name: "Designer Bags",
        originalCost: 1,
        quantity: 1,
        shippingCost: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        relatedCosts: {
          urgentPurchaseFee: 0,
          processingFee: 87000,
          shippingToOriginWarehouseCost: 87000,
          shopForMeCost: 87000,
        },
      },
    ],
    totalShopForMeCost: 87000,
  },
];

export const importOrders: ImportOrderPackageType[] = [
  {
    orderId: "OD08751",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString(),
    trackingId: "SH08751",
    shippingStatus: "not started",
    totalShippingCost: 107.76,
    shippingPaymentStatus: "Unpaid",
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "",
        deliveredBy: "Seller",
        originalCost: 0,
        quantity: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        itemDeliveryStatus: "Not yet delivered",
      },
    ],
    shipmentDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
  },
  {
    orderId: "OD08752",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString(),
    trackingId: "SH08752",
    shippingStatus: "arrived destination",
    totalShippingCost: 107.76,
    shippingPaymentStatus: "Paid",
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "",
        deliveredBy: "Seller",
        originalCost: 0,
        quantity: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        itemDeliveryStatus: "Not yet delivered",
      },
    ],
    shipmentDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
  },
  {
    orderId: "OD08753",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString(),
    trackingId: "SH08753",
    shippingStatus: "ready for shipping",
    totalShippingCost: 107.76,
    shippingPaymentStatus: "Unpaid",
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "",
        deliveredBy: "Seller",
        originalCost: 0,
        quantity: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        itemDeliveryStatus: "Not yet delivered",
      },
    ],
    shipmentDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
  },
  {
    orderId: "OD08754",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString(),
    trackingId: "SH08754",
    shippingStatus: "in transit",
    totalShippingCost: 107.76,
    shippingPaymentStatus: "Paid",
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "",
        deliveredBy: "Seller",
        originalCost: 0,
        quantity: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        itemDeliveryStatus: "Not yet delivered",
      },
    ],
    shipmentDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
  },
  {
    orderId: "OD08755",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString(),
    trackingId: "SH08755",
    shippingStatus: "processing",
    totalShippingCost: 107.76,
    shippingPaymentStatus: "Paid",
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "",
        deliveredBy: "Seller",
        originalCost: 0,
        quantity: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        itemDeliveryStatus: "Not yet delivered",
      },
    ],
    shipmentDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
  },
  {
    orderId: "OD08756",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString(),
    trackingId: "SH08756",
    shippingStatus: "cleared",
    totalShippingCost: 107.76,
    shippingPaymentStatus: "Paid",
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "",
        deliveredBy: "Seller",
        originalCost: 0,
        quantity: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        itemDeliveryStatus: "Not yet delivered",
      },
    ],
    shipmentDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
  },
  {
    orderId: "OD08757",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString(),
    trackingId: "SH08757",
    shippingStatus: "cancelled",
    totalShippingCost: 107.76,
    shippingPaymentStatus: "Unpaid",
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "",
        deliveredBy: "Seller",
        originalCost: 0,
        quantity: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        itemDeliveryStatus: "Not yet delivered",
      },
    ],
    shipmentDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
  },
  {
    orderId: "OD08758",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString(),
    trackingId: "SH08758",
    shippingStatus: "delivered",
    totalShippingCost: 107.76,
    shippingPaymentStatus: "Paid",
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "",
        deliveredBy: "Seller",
        originalCost: 0,
        quantity: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        itemDeliveryStatus: "Not yet delivered",
      },
    ],
    shipmentDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
  },
];

export const importRequests: ImportRequestPackageType[] = [
  {
    requestId: "OD08751",
    requestStatus: "Not Responded",
    requestLocalDate: new Date().toLocaleString(),
    originWarehouse: "China Warehouse (Guangzhou city)",
    deliveryStatus: "All delivered",
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "",
        deliveredBy: "Seller",
        originalCost: 1,
        quantity: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        itemDeliveryStatus: "Delivered",
      },
    ],
  },
  {
    requestId: "OD08752",
    requestStatus: "Responded",
    requestLocalDate: new Date().toLocaleString(),
    originWarehouse: "Dubai Warehouse",
    deliveryStatus: "None delivered",
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "",
        deliveredBy: "Seller",
        originalCost: 1,
        quantity: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        itemDeliveryStatus: "Not yet delivered",
      },
    ],
  },
  {
    requestId: "OD08753",
    requestStatus: "Not Responded",
    requestLocalDate: new Date().toLocaleString(),
    originWarehouse: "Nigeria Warehouse (Lagos)",
    deliveryStatus: "Some delivered",
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "",
        deliveredBy: "Seller",
        originalCost: 1,
        quantity: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        itemDeliveryStatus: "Delivered",
      },
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "",
        deliveredBy: "Seller",
        originalCost: 1,
        quantity: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        itemDeliveryStatus: "Not yet delivered",
      },
    ],
  },
  {
    requestId: "OD08754",
    requestStatus: "Responded",
    requestLocalDate: new Date().toLocaleString(),
    originWarehouse: "UK Warehouse (London)",
    deliveryStatus: "All delivered",
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "",
        deliveredBy: "Seller",
        originalCost: 1,
        quantity: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        itemDeliveryStatus: "Delivered",
      },
    ],
  },
  {
    requestId: "OD08755",
    requestStatus: "Not Responded",
    requestLocalDate: new Date().toLocaleString(),
    originWarehouse: "US Warehouse (Richmond Texas)",
    deliveryStatus: "None delivered",
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "",
        deliveredBy: "Seller",
        originalCost: 1,
        quantity: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        itemDeliveryStatus: "Not yet delivered",
      },
    ],
  },
  {
    requestId: "OD08756",
    requestStatus: "Responded",
    requestLocalDate: new Date().toLocaleString(),
    originWarehouse: "US Warehouse (Richmond Texas)",
    deliveryStatus: "Some delivered",
    items: [
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "",
        deliveredBy: "Seller",
        originalCost: 1,
        quantity: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        itemDeliveryStatus: "Not yet delivered",
      },
      {
        name: "Designer Bags",
        idType: "Tracking ID",
        idNumber: "123456789",
        deliveryStatus: "",
        deliveredBy: "Seller",
        originalCost: 1,
        quantity: 1,
        image: src,
        description: "Additonvnv ghss jgsjvsn",
        itemDeliveryStatus: "Delivered",
      },
    ],
  },
];

export const exportOrders: ExportOrderPackageType[] = importOrders;

export const exportRequests: ExportRequestPackageType[] = importRequests;

export const autoImportOrders: AutoImportOrderPackageType[] = [
  {
    orderId: "OD08756",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString(),
    trackingId: "SH08756",
    shippingStatus: "not started",
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        brand: "asd",
        model: "asd",
        productionYear: "2023",
        value: 107.76,
        condition: "Drivable",
        color: "blue",
        mileage: 0,
        vin: "asdaasd123123",
        url: "https://www.asd.com/asdasd",
        image: src,
        carTitleCopy: src,
        description: "asdasdasdasd",
      },
    ],
    shipmentDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    totalShippingCost: 107.76,
    shippingPaymentStatus: "Unpaid",
    totalClearingCost: 234000,
    clearingPaymentStatus: "Unpaid",
  },
  {
    orderId: "OD08755",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString(),
    trackingId: "SH08755",
    shippingStatus: "ready for shipping",
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        brand: "asd",
        model: "asd",
        productionYear: "2023",
        value: 107.76,
        condition: "Drivable",
        color: "blue",
        mileage: 0,
        vin: "asdaasd123123",
        url: "https://www.asd.com/asdasd",
        image: src,
        carTitleCopy: src,
        description: "asdasdasdasd",
      },
    ],
    shipmentDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    totalShippingCost: 107.76,
    shippingPaymentStatus: "Unpaid",
    totalClearingCost: 234000,
    clearingPaymentStatus: "Unpaid",
  },
  {
    orderId: "OD08754",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString(),
    trackingId: "SH08754",
    shippingStatus: "cleared",
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        brand: "asd",
        model: "asd",
        productionYear: "2023",
        value: 107.76,
        condition: "Drivable",
        color: "blue",
        mileage: 0,
        vin: "asdaasd123123",
        url: "https://www.asd.com/asdasd",
        image: src,
        carTitleCopy: src,
        description: "asdasdasdasd",
      },
    ],
    shipmentDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    totalShippingCost: 107.76,
    shippingPaymentStatus: "Paid",
    totalClearingCost: 234000,
    clearingPaymentStatus: "Paid",
  },
  {
    orderId: "OD08753",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString(),
    trackingId: "SH08753",
    shippingStatus: "processing",
    totalShippingCost: 107.76,
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        brand: "asd",
        model: "asd",
        productionYear: "2023",
        value: 107.76,
        condition: "Drivable",
        color: "blue",
        mileage: 0,
        vin: "asdaasd123123",
        url: "https://www.asd.com/asdasd",
        image: src,
        carTitleCopy: src,
        description: "asdasdasdasd",
      },
    ],
    shipmentDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    shippingPaymentStatus: "Paid",
    totalClearingCost: 234000,
    clearingPaymentStatus: "Unpaid",
  },

  {
    orderId: "OD08752",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString(),
    trackingId: "SH08752",
    shippingStatus: "in transit",
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        brand: "asd",
        model: "asd",
        productionYear: "2023",
        value: 107.76,
        condition: "Drivable",
        color: "blue",
        mileage: 0,
        vin: "asdaasd123123",
        url: "https://www.asd.com/asdasd",
        image: src,
        carTitleCopy: src,
        description: "asdasdasdasd",
      },
    ],
    shipmentDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    totalShippingCost: 107.76,
    shippingPaymentStatus: "Paid",
    totalClearingCost: 234000,
    clearingPaymentStatus: "Unpaid",
  },

  {
    orderId: "OD08751",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString(),
    trackingId: "SH08751",
    shippingStatus: "arrived destination",
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        brand: "asd",
        model: "asd",
        productionYear: "2023",
        value: 107.76,
        condition: "Drivable",
        color: "blue",
        mileage: 0,
        vin: "asdaasd123123",
        url: "https://www.asd.com/asdasd",
        image: src,
        carTitleCopy: src,
        description: "asdasdasdasd",
      },
    ],
    shipmentDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    totalShippingCost: 107.76,
    shippingPaymentStatus: "Paid",
    totalClearingCost: 234000,
    clearingPaymentStatus: "Unpaid",
  },
  {
    orderId: "OD08750",
    orderStatus: "processed",
    orderLocalDate: new Date().toLocaleString(),
    trackingId: "SH08750",
    shippingStatus: "delivered",
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        brand: "asd",
        model: "asd",
        productionYear: "2023",
        value: 107.76,
        condition: "Drivable",
        color: "blue",
        mileage: 0,
        vin: "asdaasd123123",
        url: "https://www.asd.com/asdasd",
        image: src,
        carTitleCopy: src,
        description: "asdasdasdasd",
      },
    ],
    shipmentDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    totalShippingCost: 107.76,
    shippingPaymentStatus: "Paid",
    totalClearingCost: 234000,
    clearingPaymentStatus: "Paid",
  },
];

export const autoImportRequests: AutoImportRequestPackageType[] = [
  {
    requestId: "OD08756",
    requestStatus: "Responded",
    requestLocalDate: new Date().toLocaleString(),
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        brand: "asd",
        model: "asd",
        productionYear: "2023",
        value: 107.76,
        condition: "Drivable",
        color: "blue",
        mileage: 0,
        vin: "asdaasd123123",
        url: "https://www.asd.com/asdasd",
        image: src,
        carTitleCopy: src,
        description: "asdasdasdasd",
      },
    ],
    shipmentDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    totalShippingCost: 234000,
    shippingPaymentStatus: "Paid",
    totalClearingCost: 234000,
    clearingPaymentStatus: "Unpaid",
  },
  {
    requestId: "OD08755",
    requestStatus: "Not Responded",
    requestLocalDate: new Date().toLocaleString(),
    originWarehouse: "US Warehouse (Richmond Texas)",
    items: [
      {
        brand: "asd",
        model: "asd",
        productionYear: "2023",
        value: 107.76,
        condition: "Drivable",
        color: "blue",
        mileage: 0,
        vin: "asdaasd123123",
        url: "https://www.asd.com/asdasd",
        image: src,
        carTitleCopy: src,
        description: "asdasdasdasd",
      },
    ],
    shipmentDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    billingDetails: {
      firstName: "Malibu",
      lastName: "SHedrack",
      email: "Malibushdrack@gmail.com",
      countryCode: "+234",
      phoneNumber: "803 456 7845",
      address: "No, 1osolo way, ikeja road, behind scaint merry",
      country: "Turkey",
      state: "Istanbul",
      city: "Cyprusic",
      zipPostalCode: "98765",
    },
    totalShippingCost: 234000,
    shippingPaymentStatus: "Paid",
    totalClearingCost: 234000,
    clearingPaymentStatus: "Unpaid",
  },
];

export const notificationItems: NotificationItemType[] = [
  {
    localDate: new Date().toLocaleString(),
    type: "payment confirmation",
    order: shopOrders[2]!,
  },
  {
    localDate: new Date("2022/12/12").toLocaleString(),
    type: "shipment arrival",
    order: shopOrders[2]!,
  },
  {
    localDate: new Date("2023/2/23").toLocaleString(),
    type: "payment rejection",
    order: shopOrders[0]!,
  },
];
